### ISSUE TITLE
API returns global total Confirmed cases as value 0

### ISSUE THREAD

**Issue by bilafish** [mathdroid/covid-19-api#117]
Hi @mathdroid, for some reason the API endpoint: [https://covid19.mathdro.id/api](https://covid19.mathdro.id/api) is returning value 0 for the total global confirmed and death cases.

It was working a few moments ago, I'm not sure what broke or is this expected behaviour?

<a href="https://ibb.co/4jCbnzk"><img src="https://i.ibb.co/rZqBRY9/covid19-api-29032020-2335-H.png" alt="covid19-api-29032020-2335-H" border="0"></a>

**Comment by msmfa** [comment]
Can confirm I'm also having the same problem

**Comment by leandroargentiero** [comment]
Same here. Following this thread.

**Comment by bilafish** [comment]
Also, to sanity check that it's not due to the data source, seems that the John Hopkins University CSSE dashboard is still showing correct numbers still [here](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6).

**Comment by RicardoGEsteves** [comment]
Same here. Following this thread too

**Comment by MichaelTao** [comment]
It's working again for me.

**Comment by Mozart409** [comment]
Same Here

**Comment by Mastersam07** [comment]
It was just corrected back it seems. The global death cases still shows 0.

**Comment by Mastersam07** [comment]
Came here to raise an issue and then I am not the only one experiencing it.

**Comment by Mozart409** [comment]
My Website shows the data from a hour ago. So deaths are not 0 anymore

**Comment by leandroargentiero** [comment]
Data source seems to be working again.

**Comment by bilafish** [comment]
Ok good news is that it seems that all 3 values are back to normal again. Hmm, could be an intermittent issue or delayed job I guess.

**Comment by Mastersam07** [comment]
Yea @bilafish it could be a delayed job.
