### ISSUE TITLE
Florida Data is missing

### ISSUE THREAD

**Issue by alexandprivate** [mathdroid/covid-19-api#12]
Hi there I'm noticing since last night Florida, US data is missing in the response

**Comment by mathdroid** [comment]
I have checked and there is none in the JHU itself, is the data currently wrong? If so, that's unfortunate. I'll try to relay this info to the JHU CSSE people. In the meantime, I'm going to add all known cases from all region from other sources into my own persistence layer. Hopefully it will help.

https://twitter.com/mathdroid/status/1238555398166085632?s=20

**Comment by alexandprivate** [comment]
Thank you so much!

**Comment by mathdroid** [comment]
No luck on the scraping :(

https://twitter.com/mathdroid/status/1238587022765207552?s=20

Let's add other data sources then.

**Comment by mathdroid** [comment]
Closing for this issue, will create another for exploring new data sources
