### ISSUE TITLE
chatbot for showcase

### ISSUE THREAD

**Issue by melvinalmonte** [mathdroid/covid-19-api#125]
Hey bud, built a quick chatbot with Google's dialogflow that replies with cases depending on the country the user requests. https://melv-covibot.herokuapp.com/
repo for the NextJS wrapper is here: https://github.com/melvinalmonte/covid-bot
Thanks for building this!

**Comment by k1m0ch1** [comment]
thank you! that is so cool! you can create the PR so your repo will be in our showcase
