### ISSUE TITLE
Tajikistan & Uzbekistan are apparently missing

### ISSUE THREAD

**Issue by omarjamal1** [mathdroid/covid-19-api#132]
Tajikistan & Uzbekistan are missing from the list of countries : https://covid19.mathdro.id/api/countries
also requesting their data using iso2 codes tj, and tm doesnt work: https://covid19.mathdro.id/api/countries/tj --> returns "country not found in JHU database".

**Comment by k1m0ch1** [comment]
`Uzbekistan` already available you can accessto endpoint `/api/countries/uz`

and I think data for country `Tajikistan` is not available as in mention in here https://github.com/CSSEGISandData/COVID-19/issues/1133 also I check it to worldmeter.info there is no data for country `Tajikistan` you can see here https://www.worldometers.info/coronavirus/#countries

I will close this issue
