### ISSUE TITLE
Showcasing GraphQL API I wrote

### ISSUE THREAD

**Issue by rosman21** [mathdroid/covid-19-api#149]
Here is the repo [https://github.com/rosman21/Covid-19-GraphQL-API](https://github.com/rosman21/Covid-19-GraphQL-API)

Here is the endpoint: [https://covid19-graphql-api.herokuapp.com/api/graphql](https://covid19-graphql-api.herokuapp.com/api/graphql)

Go play around with it [here](https://www.graphqlbin.com/v2/new) and let me know what you think. Only doing confirmed, recovered, and deaths totals and by country. I will be adding the ability to query by dates soon.

If anyone is interested in collaborating please reach out I am always trying to learn new stuff!!

**Comment by k1m0ch1** [comment]
thank you! that is cool! you can create the PR so your repo will be in this repo showcase

**Comment by rosman21** [comment]
I have to fork the repo in order to do this?

**Comment by k1m0ch1** [comment]
yes,
it is not a problem right now, I already add your showcase. 👍
