### ISSUE TITLE
Wrong Values for Confirmed Cases

### ISSUE THREAD

**Issue by bilafish** [mathdroid/covid-19-api#152]
Hi, there seems to be an issue with the values returned for confirmed cases.
This affects the following API endpoints (mainly time-series data):

1. https://covid19.mathdro.id/api/daily/4-13-2020 - Total summed confirmed cases = 2,019,320
2. https://covid19.mathdro.id/api/daily - Total confirmed cases on 13 Apr = 2,701,542

As of current writing (14 Apr), the total global confirmed cases is 1,918,855.

It seems to be related to an issue as reported on the data source here: [https://github.com/CSSEGISandData/COVID-19/issues/2167](https://github.com/CSSEGISandData/COVID-19/issues/2167). They have since modified the affected csv files:
- Florida data source error (4/13) - US 682,619 -> 580,619 [time_series_covid19_confirmed_global.csv]
- Okaloosa, Florida data source error (4/13) - Okaloosa, Florida 102,103 -> 103 [time_series_covid19_confirmed_US.csv]

**Comment by k1m0ch1** [comment]
I just tested this bug, I think the problem one from us is the `/daily` route
the route `/daily/<date>` already fine.

here is how I reproduce this bug https://repl.it/repls/ImmenseElementaryGenre

![image](https://user-images.githubusercontent.com/5756522/79190050-7e041600-7e4d-11ea-8b5d-9058a289b247.png)

**Comment by k1m0ch1** [comment]
fixed in https://github.com/mathdroid/covid-19-api/commit/1c523f543849f0bfa8f3055751ec83d07d5f8005
