### ISSUE TITLE
Flutter (Android/iOS) app for the showcase 

### ISSUE THREAD

**Issue by AbdullahChauhan** [mathdroid/covid-19-api#154]
Just made this beautifully design app in Flutter for the showcase:
Repo link: https://github.com/AbdullahChauhan/Coronavirus-COVID-19-Tracker

**Comment by rohmanhm** [comment]
Feel free to make a PR and submit your repo into the [Showcase](https://github.com/mathdroid/covid-19-api#showcase) section.
