### ISSUE TITLE
Last updated on daily report

### ISSUE THREAD

**Issue by bahiirwa** [mathdroid/covid-19-api#23]
Thank you for this API.

I am wondering if you can have a small `lastupdated` in the endpoint for the daily report.

**Comment by k1m0ch1** [comment]
@bahiirwa which endpoint you talking about, its the `/api/daily` endpoint?

if you refer to the `/api/daily` endpoint, you can use `reportDate` key.
if you refer to the `/api/daily/<date>` or `/api/daily/2-14-2020`  endpoint, you can use `lastUpdate` key
