### ISSUE TITLE
502: BAD_GATEWAY for the dailySummary page

### ISSUE THREAD

**Issue by keshprad** [mathdroid/covid-19-api#303]
The [dailySummary page](https://covid19.mathdro.id/api/daily) just brings up a 502: BAD_GATEWAY error. 

### Console produces this error message:
`Failed to load resource: the server responded with a status of 502 ()`
<br><br>
### Vercel displays this on the page:
`An error occurred with this application.
This is an error with the application itself, not the platform.`

**502**: BAD_GATEWAYCode:  `NO_RESPONSE_FROM_FUNCTION`
ID:  `sfo1::v4jkk-1601282194178-4cbf1e1b138f`

<br><br>
![Screen Shot 2020-09-28 at 1 45 53 AM](https://user-images.githubusercontent.com/32313895/94410568-5cad9280-012c-11eb-9975-60fb21380def.png)

**Comment by micokontic** [comment]
Yeap, I have a same problem today

**Comment by dimitrovmrtn** [comment]
Same here. Hope it gets fixed soon.

**Comment by AarshOza** [comment]
Yea I also have the same issue

**Comment by abourtnik** [comment]
Same for me also: 502 error

**Comment by npankov** [comment]
same :(

**Comment by adrianhajdin** [comment]
same problem.

**Comment by dytra** [comment]
please fix this

**Comment by welcomecurry** [comment]
having the same problem.

**Comment by rajnish8869** [comment]
I have the same problem. Error- 502: BAD_GATEWAY

**Comment by lucas-it** [comment]
I have the same problem

**Comment by ogbeche77** [comment]
I have same problem too

**Comment by kennyklee123** [comment]
Same problem

**Comment by hrshtpnt** [comment]
Same Problem `https://covid19.mathdro.id/api/daily`
**status 502**

**Comment by kermit-klein** [comment]
Same problem

**Comment by zpreston123** [comment]
Daily summary link works.  Issue can be closed.

**Comment by k1m0ch1** [comment]
Fixed in https://github.com/mathdroid/covid-19-api/pull/315
I'll close this thread
