### ISSUE TITLE
Error in Fetching daily data

### ISSUE THREAD

**Issue by the-wrong-guy** [mathdroid/covid-19-api#313]
The API path `https://covid19.mathdro.id/api/daily`  is not working

The Error  : 
502: BAD_GATEWAY
Code: NO_RESPONSE_FROM_FUNCTION
ID: bom1::xgf7d-1602310538728-ecc85cdda884

**Comment by zpreston123** [comment]
Daily summary link works.

**Comment by k1m0ch1** [comment]
Fixed in https://github.com/mathdroid/covid-19-api/pull/315
I'll close this thread
