### ISSUE TITLE
incorrect data 

### ISSUE THREAD

**Issue by jangelesg** [mathdroid/covid-19-api#34]
A request made to 

GET /api/countries/canada HTTP/1.1
Host: covid19.mathdro.id
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: close

showing this that is inaccurate 

{
  "confirmed": {
    "value": 0,
    "detail": "https://covid19.mathdro.id/api/countries/canada/confirmed"
  },
  "recovered": {
    "value": 0,
    "detail": "https://covid19.mathdro.id/api/countries/canada/recovered"
  },
  "deaths": {
    "value": 0,
    "detail": "https://covid19.mathdro.id/api/countries/canada/deaths"
  },
  "lastUpdate": "2020-03-18T19:39:34.436Z"
}

**Comment by viniciusemferreira** [comment]
Same here. Seems like it's an internal error. The OG image is showing "NaN"

![image](https://user-images.githubusercontent.com/13908734/77005437-2bf7cf80-6937-11ea-92f2-cf8ca02c38b0.png)
