### ISSUE TITLE
No data for Taiwan

### ISSUE THREAD

**Issue by frankdilo** [mathdroid/covid-19-api#46]
Hey there, thanks for this project.

Data for Taiwan seems to be missing, even if [available here](https://coronavirus.jhu.edu/map.html).

Here the endpoint returning all zeros: [covid19.mathdro.id/api/countries/TW](https://covid19.mathdro.id/api/countries/TW)

**Comment by anthlubic** [comment]
Looks like they might have changed it?  Querying for Taiwan* brings results

**Comment by frankdilo** [comment]
What do you mean by "Querying for Taiwan* brings results"?

I am trying to get daily cases for Taiwan, can you tell me which endpoint to use?

**Comment by randohinn** [comment]
@frankdilo He meant use `Taiwan*` as the Country name in your request . Seemingly there's a * being parsed as a part of the country name for Taiwan..

**Comment by frankdilo** [comment]
Thing is both Taiwan and Taiwan* map to a TW two letter country code

**Comment by mathdroid** [comment]
Hi all, sorry for not managing to triage issues fast enough. I was busy creating the Indonesia specific API (https://github.com/mathdroid/indonesia-covid-19-api). As a result, I added @anthlubic to collaborate with me in this.
