### ISSUE TITLE
South Korea not found in JHU database

### ISSUE THREAD

**Issue by ginnie7** [mathdroid/covid-19-api#47]
South Korea endpoint returns an error "not found in JHU database":

https://covid19.mathdro.id/api/countries/KR
https://covid19.mathdro.id/api/countries/KOR

**Comment by anthlubic** [comment]
this is fixed in PR #48 but if you need a temporary workaround, it can be queried using "Korea, South" as the country name like so:

https://covid19.mathdro.id/api/countries/Korea,%20South
