### ISSUE TITLE
Add deaths to api/daily

### ISSUE THREAD

**Issue by grssnbchr** [mathdroid/covid-19-api#5]
Hey, thanks for your service. Why is the "death" variable not part of the endpoint covid.mathdro.id/api/daily?

I only see total confirmed and total recovered. Would it be possible to integrate deaths as well? Thank you!

**Comment by muzzyay** [comment]
That would be nice but it seems like John Hopkins doesn't provide that data for daily.

![image](https://user-images.githubusercontent.com/45154026/76697177-7e946b80-6659-11ea-8f81-9c4068c403a2.png)
