### ISSUE TITLE
Work needed

### ISSUE THREAD

**Issue by kibertoad** [mathdroid/covid-19-api#55]
I'm a backend Node.js developer and I would like to contribute. Is there any work I can do that wouldn't overlap with what is already being done?

**Comment by k1m0ch1** [comment]
hi @kibertoad you could check this issue to help us :
https://github.com/mathdroid/covid-19-api/issues/10
https://github.com/mathdroid/covid-19-api/issues/11
or any issue with label `enhancement`

and then you just create a new PR, thanks for your attention!
