### ISSUE TITLE
Country data outside of US not available

### ISSUE THREAD

**Issue by wesbos** [mathdroid/covid-19-api#6]
Looks like none of these endpoints are currently working:

https://covid19.mathdro.id/api/countries/CA
https://covid19.mathdro.id/api/countries/CN
https://covid19.mathdro.id/api/countries/Indonesia

Are they currently down? 

Thanks for making this!

**Comment by mathdroid** [comment]
Hi @wesbos, glad to see you here! It seems like an upstream problem, they seem to be currently down from my side too. If you have any idea on how to mitigate this I'm all ears! Meanwhile, I'll tighten the caching on the production site so they will get reduced load

![image](https://user-images.githubusercontent.com/3748658/76537911-07bc6e80-64b1-11ea-9507-57218ee6acd5.png)

![image](https://user-images.githubusercontent.com/3748658/76538206-887b6a80-64b1-11ea-954e-f5318d8c995b.png)

**Comment by jperl** [comment]
A simple thing to do would be to just cache everything in Postgres. Do a lot of the requests overlap?

**Comment by jperl** [comment]
Seems like it's no longer a problem?

**Comment by jgbijlsma** [comment]
I, I got the same problem for a lot of countries. Mainland China (CN) is one pretty important one.

**Comment by mathdroid** [comment]
JHU changed some of the countries' names, including China. I have now fixed querying those countries by ISO codes. https://covid19.mathdro.id/api/countries/CN https://covid19.mathdro.id/api/countries/CHN

(Normal search was actually unaffected https://covid19.mathdro.id/api/countries/china)

@jgbijlsma

**Comment by mathdroid** [comment]
I will close this as the issue from the title is resolved, will make another issue for data persistence. Tag: @jperl
