### ISSUE TITLE
global cases per region sorted by confirmed cases (api/confirmed)

### ISSUE THREAD

**Issue by jnameir** [mathdroid/covid-19-api#60]
fetch request from e.g. https://covid19.mathdro.id/api/countries/us
--> confirmed cases can be accessed by data.confirmed.value

Wanting to create a table of countries sorted by confirmed death cases...
how can i access the endpoints from https://covid19.mathdro.id/api/confirmed ? 

Thanks!

**Comment by k1m0ch1** [comment]
if you want to sorted by confirmed death cases, you can use the endpoint `/api/deaths` (https://covid19.mathdro.id/api/deaths)

I will close this issue
