### ISSUE TITLE
Python/Flask App Using COVID-19-API

### ISSUE THREAD

**Issue by DykemaBill** [mathdroid/covid-19-api#64]
# [virustracker](https://github.com/DykemaBill/virustracker)

Python Flask application that displays virus information in a customizable format

# Description

Web application written in Python using Flask which provides a single root page to display current World and customizable country COVID-19 information.  This application reads from a configuration file which can be used to customize the following:

- Support email address for your page
- Page logo (set to [World Health Organization](http://who.int)'s logo by default)
- API root (set to [Muhammad Mustadi](https://mathdro.id)'s [COVID-19 JSON API](https://github.com/mathdroid/covid-19-api) by default)
- Countries, can be used to set the countries you would like to see information on

[https://github.com/DykemaBill](https://github.com/DykemaBill)

![virustracker_screenshot](https://github.com/DykemaBill/virustracker/blob/master/virustrackerSS.png)

**Comment by k1m0ch1** [comment]
That's pretty cool!!
you actually can add a new showcase by creating a PR to this repo
