### ISSUE TITLE
Data is not refreshing

### ISSUE THREAD

**Issue by melihceyhan** [mathdroid/covid-19-api#72]
Is there any problem? Data is not refreshing for 7-8 hours

**Comment by mithhu** [comment]
https://twitter.com/mathdroid/status/1242093423361851398

"The feature layer got deprecated today. Please wait until there's solution.", Muhammad Mustadi

**Comment by randohinn** [comment]
@mathdroid Assuming daily endpoint not having today's data at all be connected to this.

**Comment by k1m0ch1** [comment]
I assume this is solved because data is already updated.
