### ISSUE TITLE
Corona Tracker Angular SPA using Covid-19-API

### ISSUE THREAD

**Issue by JakMar17** [mathdroid/covid-19-api#75]
Corona tracker written in Angular, shows graphs and other information about COVID-19 spreading around the world.

Website: [Corona Tracker](https://tracking-corona.web.app/)
GitHub Repo: [CoronaTracker](https://github.com/JakMar17/CoronaTracker)

**Comment by k1m0ch1** [comment]
thank you! that is so cool! you can create the PR so your repo will be in our showcase
