### ISSUE TITLE
Data from Indonesia (ID/IDN) is missing

### ISSUE THREAD

**Issue by skymunn** [mathdroid/covid-19-api#85]
# Summary
Data from Indonesia with code ID/IDN is missing from the API

# Produce
Go to `api/countries/ID` and you can see confirmed/recovered/deaths count are 0.

# Expected Results
Client can see last update from Indonesia

# Actual Results
The data is empty.
![image](https://user-images.githubusercontent.com/32958839/77382909-8d4af300-6dbc-11ea-99e5-ff7e2e2ade1f.png)
![image](https://user-images.githubusercontent.com/32958839/77382916-9340d400-6dbc-11ea-8e1a-f9bb0a0fc975.png)

I bring you some proof of image to make this bug report more actual. Thanks before.

**Comment by rizki5411** [comment]
It's not bug system, it's bug on yourselft.
end poin for indonesia not,
https://covid19.mathdro.id/api/countries/ID

but
https://covid19.mathdro.id/api/countries/Indonesia

**Comment by skymunn** [comment]
@rizki5411 Well, maybe the creator just fix this bug. If you know, we can using ISO-Alpha2/3 to call details from the countries. I'll close this issues.
![image](https://user-images.githubusercontent.com/32958839/77453012-9e821700-6e31-11ea-8589-02f46cbb1ee7.png)
