### ISSUE TITLE
recovered data on /daily always return 0

### ISSUE THREAD

**Issue by rizki5411** [mathdroid/covid-19-api#89]
end point of `https://covid19.mathdro.id/api/daily`

![image](https://user-images.githubusercontent.com/31713769/77453837-5b707580-6e2a-11ea-8a08-0db43fb7049f.png)

**Comment by YogaSakti** [comment]
TotalRecovered data is missing from JHU’s feature layers

**Comment by Sridatta19** [comment]
JHU stopped reporting recovered cases

**Comment by rizki5411** [comment]
> 
> 
> JHU stopped reporting recovered cases

why? and where we can get it again?
