### ISSUE TITLE
/countries changed? 

### ISSUE THREAD

**Issue by ransing** [mathdroid/covid-19-api#90]
Previously https://covid19.mathdro.id/api/countries used to return two objects (one with an array of countries and one with a ISO code) but now it returns an array of objects for each country.
Is it possible for to make another page with the previous pattern of countries?
Or if that json information  exists somewhere I can make my own.

**Comment by mikemcbride** [comment]
FWIW, you should be able to reconstruct the old structure based on the new data. All the information is still there. Here's a JS function you could run that would give you the old data:

```js
// where "data" is the result from the API call to /api/countries
let oldStructure = {
  countries: {},
  iso3: {}
}

for (let country of data) {
  countries[country.name] = country.iso2
  iso3[country.iso2] = country.iso3
}

// now "oldStructure" is an object with the shape that it previously had
```
